#!/usr/bin/env bash

echo "Setting up MySQL users."

mysql -uroot -ppassword  -e "GRANT ALL PRIVILEGES ON \`$DB_SCHEMA\`.* TO '$USERNAME'@'$WEB_IP_ADDR' IDENTIFIED BY '$PASSWORD' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
FLUSH PRIVILEGES;"